
spring:
  application:
    name: E-Store

  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/e-store
    username: postgres
    password: mmk7
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true

  # DevTools Configuration
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
    livereload:
      enabled: true
    add-properties: false

# Optional: Logging SQL statements (debugging)
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE